name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below
    if: ${{ github.repository_owner == 'shaonhuang' }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and YARN V3
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install Yarn v3
        run: npm install -g yarn@3

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: |
          yarn electron-vite build
      - name: Pack for Mac
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASS }}
        run: yarn electron-builder -m
      - name: Pack for Windows
        run: yarn electron-builder -w
      - name: Pack for Linux
        run: yarn electron-builder -l
      - name: Publish prereleases
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASS }}
          # CSC_LINK: ${{ secrets.CSC_LINK }}
          # CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          yarn electron-builder -lmw --publish always
