name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  mac-publish:
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below
    if: ${{ github.repository_owner == 'shaonhuang' }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-13]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install latest Yarn
        run: npm install -g yarn@berry

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: |
          yarn electron-vite build

      - name: Fix Clean Up issue
        run: |
          sudo mdutil -a -i off

      - name: Cancel code sign and Pack for Mac and release
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # CSC_LINK: ${{ secrets.CSC_LINK }}
          # CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
          command: yarn electron-builder -m -p always

  win-publish:
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below
    if: ${{ github.repository_owner == 'shaonhuang' }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install latest Yarn
        run: npm install -g yarn@berry

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: |
          yarn electron-vite build

      - name: Pack for Windows and release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
          command: yarn electron-builder -w -p always

  linux-publish:
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below
    if: ${{ github.repository_owner == 'shaonhuang' }}

    runs-on: ${{ matrix.os }}

    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v2

      - name: Install latest Yarn
        run: npm install -g yarn@berry

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: |
          yarn electron-vite build

      - name: Pack for Linux and release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
          command: yarn electron-builder -l -p always
