name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  mac-publish:
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below
    if: ${{ github.repository_owner == 'shaonhuang' }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install latest Yarn
        run: npm install -g yarn@berry

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: |
          yarn electron-vite build

      - name: Pack for Mac and release
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn electron-builder -m -p always

  win-publish:
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below
    if: ${{ github.repository_owner == 'shaonhuang' }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install latest Yarn
        run: npm install -g yarn@berry

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: |
          yarn electron-vite build

      - name: Pack for Windows and release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn electron-builder -w -p always

  linux-publish:
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below
    if: ${{ github.repository_owner == 'shaonhuang' }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install latest Yarn
        run: npm install -g yarn@berry

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: |
          yarn electron-vite build

      - name: Pack for Linux and release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn electron-builder -l -p always
